name: E2E_DevSecOps

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  LINT:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: true
          DISABLE_ERRORS: true
  SCA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven-3-jdk-17@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
       sarif_file: snyk.sarif
  DAST:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: setup maven
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            server-id: 'github'
            settings-path: '${{ github.workspace }}'
            cache: maven

        - name: Build with maven
          run: |
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=dia_snky-vul-java-app
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}